### PR TITLE
Ignores git clone errors

### LINKED ISSUE #253: fatal: destination path 'faros-community-edition' already exists and is not an empty directory.
**Describe the bug**

```
fatal: destination path 'faros-community-edition' already exists and is not an empty directory.
```

**To Reproduce**
1. run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/faros-ai/faros-community-edition/main/install.sh)" _ --source doc_welcome`
2. stop it
3. run it again `$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/faros-ai/faros-community-edition/main/install.sh)" _ --source doc_welcome`

**Expected behavior**

If the destination directory exists, stop the script or cd git pull latest

### PR DESCRIPTION
**Pull request by thomas-gerber**
# Description

Simply ignores `git clone` errors.

We could do something more involved but:
* we would need to handle cases where the directory is a git directory vs not (pull vs stop the script)
* in the future, the install script will probably just pull the necessary files (`docker-compose.yaml`, `.env` and `start.sh`), so no need for something drastic now

Fixes #253

## Type of change
- Bug fix (non-breaking change which fixes an issue)

# Checklist
(Delete what does not apply)
- [x] Have you checked to there aren't other open Pull Requests for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #!/bin/bash
 
-git clone https://github.com/faros-ai/faros-community-edition.git
+git clone https://github.com/faros-ai/faros-community-edition.git || true
 cd faros-community-edition || exit
```
Comment (tovbinm) [inline install.sh:4]: `cd faros-community-edition && git pull || exit`

**Review by tovbinm — APPROVED** [review]
